version: '3'
services:
  app:
    image: node:14
    container_name: todo-app
    ports:
      - "80:3000" # Map port 80 on host to 3000 inside container
    volumes:
      - .:/app
    command: ["npm", "start"]
